### ISSUE TITLE
Reloaded tab sets come back rearranged

### ISSUE THREAD

**Issue by mmatti** [42Squares/LightPaper#57] opened 2016-02-20 14:46 UTC
Here's a funny one: suppose you've got four documents open, then quit. LightPaper reloads those documents when you return, which is genuinely helpful behavior.

What's a little less helpful is that they often come back rearranged: the document that was the 4th tab is now in the 3rd position, and later might show up in the 2nd or 1st spot. I've been opening and closing LightPaper for a while trying to spot a clear pattern, but haven't been able to nail it down.

But go ahead and try it; the position shift kicks in pretty frequently.

Running version 1.3 final.

**Comment by ashokgelal** [comment] 2016-02-21 06:03
I'm actually aware of this issue and spent some time trying to fix it. The problem is with the asynchronous nature of file loading (so that loading of one file doesn't block loading of another file). This also annoys me a lot too and will be fixed but I might need to do some intense refactoring to support this.

**Comment by ashokgelal** [comment] 2016-03-01 16:13
This should now be fixed in 1.4 alpha

**Comment by mmatti** [comment] 2016-03-01 16:55
Cool. Seems to be working fine so far, we'll see how it holds up ...

Much appreciated.

**Closed** 2016-03-12 04:13 UTC
